datamodule:
  _target_: lib.dataset.cape.CAPEDataModule
  dataset_path: ./data/CAPE
  num_workers: 0
  subject: ${subject}
  clothing: 'blazerlong'
  batch_size: 8
  processor:
    _target_: lib.dataset.cape.CAPEDataProcessor
    points_per_frame: 2000
    sampler:
      _target_: lib.model.sample.PointInSpace
      global_sigma: 1.8
      local_sigma: 0.01
